version: 0.0
os: linux
files:
   - source: /home/ubuntu
     destination: /home/ubuntu
permissions:
   - object: /home/ubuntu
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
      AfterInstall:
    - location: /scripts/bundle.rb
   
