version: 0.0
os: linux
files:
   - source: /home/ubuntu
     destination: /home/ubuntu
permissions:
   - object: /home/ubuntu
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   #BeforeInstall:
   # - location: scripts/installapache.sh ccc
   #   runas: root vvvv
    #- location: scripts/startapache.sh
    #  runas: root
   AfterInstall:
    - location: ./scripts/bundle.rb
    #  runas: root
    #- location: scripts/restartapache.sh

#runas: root
