version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/codeship_test
permissions:
   - object: /home/ubuntu/codeship_test
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: scripts/createbackup.sh
      timeout: 300
      runas: root
  AfterInstall: 
    - location: scripts/bundle.rb
      timeout: 300
      runas: root
    - location: scripts/restartpassenger.sh
      timeout: 300
      runas: root
  
