version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/codeship_test
permissions:
   - object: /home/ubuntu/codeship_test
     pattern: "**"
     type:
       - file
hooks:
  BeforeInstall:
    - location: scripts/createbackup.sh
      timeout: 300

  AfterInstall: 
    - location: scripts/bundle.sh
      timeout: 300
      
    
