version: 0.0
os: linux
files:
   - source: /home/ubuntu/codeship_test
     destination: /home/ubuntu/codeship_test
permissions:
   - object: /home/ubuntu/codeship_test
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
      AfterInstall:
       - location: scripts/bundle.rb
         timeout: 300
         runas: root
   
